# Generated by Django 5.0.6 on 2024-06-02 11:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors_app', '0002_alter_quote_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='quote',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=None, max_length=255), default=None, size=None),
            preserve_default=False,
        ),
    ]
